### ISSUE TITLE
Add auto-redirect for appium automation

### ISSUE THREAD

**Issue by rpappalax** [jrconlin/Webpush_QA#1]
to automate using appium (in emulator), we'll need to report test results in a non-browser-content manner.  Perhaps redirecting (when all tests finish) to same page with test results as params.

Something like:
https://jrconlin.github.io/Webpush_QA?test1=pass&test2=pass&test3=fail

@npark-mozilla would this work w/ appium?

For manual testing, it would be helpful if we could retain the ability to stay on same page and view results as we currently do.  Perhaps something like:
https://jrconlin.github.io/Webpush_QA?manual=true

**Comment by nojunpark** [comment]
Since Appium only provides interface to manipulate the android app's java view, (and not the gecko view which renders the browser content) as Richard says we need to read the test results somewhere else.  If the redirection is automatic, maybe it'll work, but I haven't tried automatic url redirection with android yet (I'm guessing it'll work) .  I was thinking more primitive ways of obtaining the test result, like go to https://jrconlin.github.io/Webpush_QA/results.txt and download the result, which will always contain the test results of the latest run.  But automatic redirection sounds cool.

**Comment by rpappalax** [comment]
@npark-mozilla the page is client-side only so that may not be to viable.  Let's experiment with appium page-redirects then let @jrconlin know if that works before he makes any changes
